services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ./data:/app/data
      - ./minecraft:/app/minecraft
    environment:
      - DISCORD_TOKEN=YOUR_DISCORD_TOKEN

      - WELCOME_CHANNEL_ID=123456789
      - MC_STATUS_CHANNEL_ID=123456789
      - MC_INFO_CHANNEL_ID=123456789
      - STEAM_WISHLIST_CHANNEL_ID=123456789

      - NEW_MEMBER_ROLE_ID=123456789

      - STEAM_ID=YOUR_STEAM_ID
      
      - TV_IP=YOUR_SAMSUNG_TV_IP