services:
  bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

    extra_hosts:
      - "host.docker.internal:host-gateway"