services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    privileged: true

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./data:/app/data
      - ./minecraft:/app/minecraft
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      MC_DATA_PATH: ${PWD}/minecraft

    env_file:
      - .env
